### ISSUE TITLE
browse-messages not found for messages org.apache.activemq.command.ActiveMQObjectMessage

### ISSUE THREAD

**Issue by joeldelvalle** [antonwierenga/amazonmq-cli#3]
when I try to browse message from specific queue, I had this error

Command failed java.lang.ClassCastException: org.apache.activemq.command.ActiveMQObjectMessage cannot be cast to javax.jms.TextMessage
java.lang.ClassCastException: org.apache.activemq.command.ActiveMQObjectMessage cannot be cast to javax.jms.TextMessage
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1$$anonfun$apply$5.apply(MessageCommands.scala:215)
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1$$anonfun$apply$5.apply(MessageCommands.scala:212)
	at amazonmq.cli.command.Commands.withSession(Commands.scala:116)
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1.apply(MessageCommands.scala:212)
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1.apply(MessageCommands.scala:210)
	at amazonmq.cli.command.Commands.withWebClient(Commands.scala:139)
	at amazonmq.cli.command.MessageCommands.browseMessages(MessageCommands.scala:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
	at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:50)
	at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
	at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
	at java.lang.Thread.run(Thread.java:748)

**Comment by antonwierenga** [comment]
Hi,

Currently amazonmq-cli only supports text messages (javax.jms.TextMessage). Your queue contains an object message (ActiveMQObjectMessage).

Regards,

Anton

**Comment by joeldelvalle** [comment]
OK, thanks
