### ISSUE TITLE
malformed url exception

### ISSUE THREAD

**Issue by asok1** [antonwierenga/amazonmq-cli#4]
I have my environment set up with activemq-5.16.0 and amazonmq-cli-0.2.2 as well as Java 8.

Running any valid command within the cli throws the following exceptions:

`local>list-queues`
```Command failed java.lang.reflect.UndeclaredThrowableException
java.net.MalformedURLException: no protocol: /xml/queues.jsp
        at java.net.URL.<init>(URL.java:610)
        at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlUnsafe(UrlUtils.java:243)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:450)
        at amazonmq.cli.command.QueueCommands$$anonfun$listQueues$1.apply(QueueCommands.scala:162)
        at amazonmq.cli.command.QueueCommands$$anonfun$listQueues$1.apply(QueueCommands.scala:161)
        at amazonmq.cli.command.Commands.withWebClient(Commands.scala:139)
        at amazonmq.cli.command.QueueCommands.listQueues(QueueCommands.scala:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
        at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:50)
        at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
        at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
        at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
        at java.lang.Thread.run(Thread.java:748)
java.lang.reflect.UndeclaredThrowableException
    at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:315)
    at org.springframework.util.ReflectionUtils.handleInvocationTargetException(ReflectionUtils.java:295)
    at org.springframework.util.ReflectionUtils.handleReflectionException(ReflectionUtils.java:279)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:219)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:50)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.MalformedURLException: no protocol: /xml/queues.jsp
    at java.net.URL.<init>(URL.java:610)
    at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlUnsafe(UrlUtils.java:243)
    at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:450)
    at amazonmq.cli.command.QueueCommands$$anonfun$listQueues$1.apply(QueueCommands.scala:162)
    at amazonmq.cli.command.QueueCommands$$anonfun$listQueues$1.apply(QueueCommands.scala:161)
    at amazonmq.cli.command.Commands.withWebClient(Commands.scala:139)
    at amazonmq.cli.command.QueueCommands.listQueues(QueueCommands.scala:161)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    ... 6 more
```

Could this be an issue with my setup? Where should I start looking?

**Comment by antonwierenga** [comment]
Hi, 

It looks as if the ActiveMQ Web Console is not configured correct. ActiveMQ Web Console is required for amazonmq-cli to function properly. Do you have ActiveMQ Web Console running and is it configured correctly in your amazonmq-cli.config?

"web-console = "https://your-amazon-mq-broker-host:8162/admin/"
