### ISSUE TITLE
Command failed java.lang.NoClassDefFoundError: com/thoughtworks/xstream/converters/Converter

### ISSUE THREAD

**Issue by cogito-njaiswal** [antonwierenga/amazonmq-cli#5]
Command failed java.lang.NoClassDefFoundError: com/thoughtworks/xstream/converters/Converter
java.lang.ClassNotFoundException: com.thoughtworks.xstream.converters.Converter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.activemq.transport.xstream.XStreamWireFormatFactory.createWireFormat(XStreamWireFormatFactory.java:31)
	at org.apache.activemq.transport.TransportFactory.createWireFormat(TransportFactory.java:193)
	at org.apache.activemq.transport.TransportFactory.doConnect(TransportFactory.java:119)
	at org.apache.activemq.transport.TransportFactory.connect(TransportFactory.java:65)
	at org.apache.activemq.ActiveMQConnectionFactory.createTransport(ActiveMQConnectionFactory.java:331)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:346)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
	at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
	at amazonmq.cli.command.Commands.withSession(Commands.scala:112)
	at amazonmq.cli.command.BrokerCommands.connect(BrokerCommands.scala:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:196)
	at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
	at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:48)
	at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:127)
	at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)

**Comment by cogito-njaiswal** [comment]
> Command failed java.lang.NoClassDefFoundError: com/thoughtworks/xstream/converters/Converter
> java.lang.ClassNotFoundException: com.thoughtworks.xstream.converters.Converter
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> at org.apache.activemq.transport.xstream.XStreamWireFormatFactory.createWireFormat(XStreamWireFormatFactory.java:31)
> at org.apache.activemq.transport.TransportFactory.createWireFormat(TransportFactory.java:193)
> at org.apache.activemq.transport.TransportFactory.doConnect(TransportFactory.java:119)
> at org.apache.activemq.transport.TransportFactory.connect(TransportFactory.java:65)
> at org.apache.activemq.ActiveMQConnectionFactory.createTransport(ActiveMQConnectionFactory.java:331)
> at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:346)
> at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
> at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
> at amazonmq.cli.command.Commands.withSession(Commands.scala:112)
> at amazonmq.cli.command.BrokerCommands.connect(BrokerCommands.scala:70)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:196)
> at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
> at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:48)
> at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:127)
> at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
> at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)

Please help me this immediately

**Comment by antonwierenga** [comment]
You can try putting the appropriate [xstream](https://x-stream.github.io/download.html) JAR into the amazonmq-cli/lib/ folder.
