### ISSUE TITLE
ActiveMQBytesMessage cannot be cast to javax.jms.TextMessage

### ISSUE THREAD

**Issue by dirkaholic** [antonwierenga/amazonmq-cli#6]
When browsing messages we infrequently get the following exception. Our messages have an XML document as body but it is not clear what is different to other messages that do not get the exception.

```
Command failed java.lang.ClassCastException: org.apache.activemq.command.ActiveMQBytesMessage cannot be cast to javax.jms.TextMessage
java.lang.ClassCastException: org.apache.activemq.command.ActiveMQBytesMessage cannot be cast to javax.jms.TextMessage
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1$$anonfun$apply$5.apply(MessageCommands.scala:215)
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1$$anonfun$apply$5.apply(MessageCommands.scala:212)
	at amazonmq.cli.command.Commands.withSession(Commands.scala:116)
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1.apply(MessageCommands.scala:212)
	at amazonmq.cli.command.MessageCommands$$anonfun$browseMessages$1.apply(MessageCommands.scala:210)
	at amazonmq.cli.command.Commands.withWebClient(Commands.scala:139)
	at amazonmq.cli.command.MessageCommands.browseMessages(MessageCommands.scala:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
	at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:50)
	at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
	at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by antonwierenga** [comment]
The difference is that the messages that do not get the exception are of type javax.jms.TextMessage.

Is it possible that the messages that are causing exceptions are sent by a producer that is sending them as ByteMessage?

**Comment by dirkaholic** [comment]
Hello, as I'm not producing these messages myself I'm not exactly sure how it is done but the respective developers are saying that all messages are produced in the same way but I can not validate that.

**Comment by antonwierenga** [comment]
Since activemq-cli currently only supports messages of type javax.jms.TextMessage this error won't go away.
